service: proyecto-final-pedidos
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true

functions:
  realizarfinalpedidosaws:
    handler: handler.realizarfinalpedidosaws
    events:
      - http:
          method: POST
          path: /realizarfinalpedidosaws
  recibirfinalpedidosaws:
    handler: handler.recibirfinalpedidosaws
    events:
      - http:
          method: GET
          path: /recibirfinalpedidosaws

resources:
  Resources:
    Bucketdeos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: order-backup-bucket-trabajo-final-osneiderdeicy
        LifecycleConfiguration:
          Rules:
            - Id: DeleteAfterTwoDays
              Status: Enabled
              ExpirationInDays: 2

    Basededatosdeos:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: centrocomercial
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        Engine: MySQL
        EngineVersion: 5.7
        MasterUsername: admin
        MasterUserPassword: 1234567890
        MultiAZ: false
        StorageType: gp2
        PubliclyAccessible: true
        VPCSecurityGroups:
          - sg-04487a4bb0ebb03d5

    RDSSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId: sg-04487a4bb0ebb03d5
        IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0

    Queuedeos:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: order-queue
        DelaySeconds: 15
        MessageRetentionPeriod: 1209600
